thomaslacan/beatween

.gitignore

adding the dotenv

---

Gemfile
Gemfile.lock
app/models/song.rb
app/models/track.rb
app/models/user.rb
app/uploaders/photo_uploader.rb
app/uploaders/track_uploader.rb

added cloudinary carrierwave and uploaders

---

app/uploaders/photo_uploader.rb
app/uploaders/track_uploader.rb
db/migrate/20180827140302_add_photo_to_users.rb
db/migrate/20180827140311_add_photo_to_songs.rb
db/migrate/20180827140435_add_track_id_to_tracks.rb
db/schema.rb

added photos to users and songs and track ids to tracks

---

db/seeds.rb

seeds to test

---

db/schema.rb
db/seeds.rb

seeds clean clean

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/songs/_index.scss
app/assets/stylesheets/songs/_show.scss
app/controllers/songs_controller.rb
app/views/songs/show.html.erb
db/schema.rb

songs show basics done

---

app/assets/stylesheets/songs/_card.scss
app/views/songs/_card.html.erb
app/views/songs/index.html.erb

basic card design css - js missing

---

app/assets/stylesheets/layouts/_index.scss
app/assets/stylesheets/songs/_card.scss
app/assets/stylesheets/songs/_index.scss
app/javascript/packs/application.js
app/javascript/packs/card.js
app/views/songs/_card.html.erb

added js etc

---

app/assets/stylesheets/components/_navbar.scss

experience button simple style

---

app/assets/stylesheets/songs/_card.scss
db/schema.rb
db/seeds.rb

fixed seeds and margin on index

---

app/assets/stylesheets/songs/_card.scss
app/assets/stylesheets/songs/_index.scss
app/javascript/packs/application.js
app/javascript/packs/colorize.js
app/javascript/packs/search.js
app/views/songs/index.html.erb

basics search done. form to go

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/songs/_index.scss
app/controllers/songs_controller.rb
app/models/song.rb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/songs/index.html.erb
db/schema.rb

pg search basics

---

app/models/instrument.rb
db/migrate/20180829143638_add_instrument_type_to_tracks.rb
db/migrate/20180829150044_create_instruments.rb
db/schema.rb
db/seeds.rb
test/models/instrument_test.rb

@ghbozz @AntoineCoconut 
New seeds par contre j'ai du suppr la migration add instrument type to track donc c ok je crois !

Tom intrument type

---

app/controllers/tracks_controller.rb
app/policies/track_policy.rb
app/views/shared/_footer.html.erb
app/views/tracks/new.html.erb

track new tbc

---

app/controllers/tracks_controller.rb
app/views/tracks/new.html.erb

tracks#controller 
def new
def create

track new and create

---

app/controllers/tracks_controller.rb
app/views/songs/show.html.erb
app/views/tracks/destroy.html.erb
app/views/tracks/edit.html.erb
config/routes.rb

j'ai commenté les edit update et delete des tracks tbc........

edit update destroy tbc

---

app/javascript/packs/player/player.js

io j'ai désactiver les btn mute qd au moins un solo est actif
pour le moment c tres sale au niveau du code je vais refacto tt ca...
mais ca marche

inactive mute when solo

---

app/javascript/packs/player/player.js

toggle du btn play qd la lecture se termine

toggle play btn when end

---

app/assets/stylesheets/songs/_show.scss
app/views/songs/show.html.erb

io j'ai essayer un truc vite fait sur la show des song, j'ai ajouter une div en haut qui contient les infos de la song. j'ai mis la photo de la song en background mais je c pas pourquoi elle ne prend la le 100vw !!!!
Antoine si tu peut jeter un oeil plzzzz ca me rend fou

song show front tweek

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/player/_index.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

petit footer vite fait, pas incroyable tbc !

footer tweek

---

db/seeds.rb

Seeds fixed

---

app/views/shared/_menu.html.erb

ajout d'un btn add song sur la show des songs (tres sale tbc....)

add song btn

---

app/controllers/songs_controller.rb
app/views/songs/show.html.erb

track pending only for song owner

tracks pending front tbc

---

app/views/songs/_card.html.erb

username on cards

---

app/javascript/packs/card.js

fix du mouse over sur les cards

fix mouseover on card

---

app/controllers/songs_controller.rb
app/models/song.rb

Durations are now stored in ms

duration stored in ms

---

app/assets/stylesheets/player/_index.scss
app/views/songs/show.html.erb

show song tweek

---

app/assets/stylesheets/player/_index.scss
app/javascript/packs/player/player.js
app/views/songs/show.html.erb

2edit pull request pour la meme branche j'ai fait de la merde mais bon
on peut bouger dans l'audio
la playhead bouge enfin mais y'a qd meme une merde je t'expliquerai (mais c mieu que rien)

audio jumping timecode

---

app/models/track.rb
app/views/tracks/new.html.erb

j'ai viré le bpm sur les new track ca n'avais pas de sens...

remove bpm on new track

---

app/views/songs/show.html.erb

ajout des btn delete.
sur tte les track pour le song owner
juste mes track pour un simple user

delete btn on song owner and user

---

app/assets/javascripts/application.js
app/assets/stylesheets/components/_menu.scss
app/assets/stylesheets/songs/_index.scss
app/javascript/packs/application.js
app/javascript/packs/search.js
app/views/layouts/application.html.erb
app/views/shared/_menu.html.erb
app/views/songs/_search.html.erb
app/views/songs/index.html.erb

fixed search once and for all

---

app/assets/stylesheets/songs/_index.scss
app/javascript/packs/application.js
app/javascript/packs/colorize.js

colorize search back

---

app/views/tracks/new.html.erb

fix new track simple form

---

app/assets/stylesheets/users/_show.scss
app/views/users/show.html.erb

petit fix sur la user show My songs/Username songs

user show fix my songs / name songs

---

app/assets/stylesheets/songs/_show.scss
app/javascript/packs/player/player.js
app/views/songs/show.html.erb

player fix playhead

---

app/assets/stylesheets/layouts/_index.scss
app/views/devise/sessions/new.html.erb

login form

---

app/assets/stylesheets/users/_show.scss
app/views/users/show.html.erb

petit tweek sur le user show pour ne pas voir 0 pending tracks

pending tracks on user profil tweek

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/songs/_show.scss
app/assets/stylesheets/tracks/_index.scss
app/assets/stylesheets/tracks/_new.scss
app/views/songs/new.html.erb
app/views/tracks/new.html.erb
db/seeds.rb

fin de journée full form mais pas finit

pas mal mais pas finit

---

app/assets/stylesheets/songs/_show.scss
app/javascript/packs/player/track.js

mute btn colorize

---

app/views/users/show.html.erb

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Ca va peut etre entré en conflit avec ma précédente PR mais c rien de grave j'éditerais

tweek on user show pending tracks or not

---

app/controllers/tracks_controller.rb
app/models/song_track.rb
app/models/track.rb

le validates des track est ok a priori mais faudra test avec le compte cloudinary vierge

validates track uploading

---

app/views/songs/new.html.erb

just remove the "Add song" h3 in html

remove add song h3

---

app/assets/stylesheets/components/_footer.scss
app/views/shared/_footer.html.erb

social links hover

---

app/assets/stylesheets/users/_show.scss
app/views/users/show.html.erb

mauvais nom de branch, 
ajout du nombre de tracks 'active' dans mes collabs (sur le user profil)

active track on collabs

---

db/seeds.rb

seeds v5434566
